### ISSUE TITLE
IllegalArgumentException: duplicate element

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#100]
This error popped out while or after saving the Java file:
```
eclipse.buildId=4.24.0.I20220425-1800
java.version=11.0.10
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.jobs
Error
Wed Apr 27 13:37:16 CEST 2022
An internal error occurred during: "Periodic workspace save.".

java.lang.IllegalArgumentException: duplicate element: ElementTree(3956->3957...3962)
	at java.base/java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:604)
	at java.base/java.util.Set.of(Set.java:701)
	at org.eclipse.core.internal.resources.SaveManager.sortTrees(SaveManager.java:1555)
	at org.eclipse.core.internal.resources.SaveManager.collapseTrees(SaveManager.java:324)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1212)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1147)
	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

@jukzi : this is from recent changes in #34. Does this stack provides enough info to understand what's went wrong, or should the report be complemented with additional data (files, checks etc)? Haven't checked the code yet.

**Comment by iloveeclipse** [comment]
The errors keep popping in same workspace / session, but using different ID's:
```
java.lang.IllegalArgumentException: duplicate element: ElementTree(4211->4212...4226)
	at java.base/java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:604)
	at java.base/java.util.Set.of(Set.java:701)
	at org.eclipse.core.internal.resources.SaveManager.sortTrees(SaveManager.java:1555)
	at org.eclipse.core.internal.resources.SaveManager.collapseTrees(SaveManager.java:324)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1212)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1147)
	at org.eclipse.core.internal.resources.DelayedSnapshotJob.run(DelayedSnapshotJob.java:51)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by iloveeclipse** [comment]
OK, that error popped on every workspace save task (every 5 minutes) in the session, so I've restarted. On shutdown, it finally printed a bit more information, the file/directory in question were both writable & overridden on restart. So that looks like some internal issue not caused by any file IO troubles or the like.

```
eclipse.buildId=4.24.0.I20220425-1800
java.version=11.0.10
java.vendor=Red Hat, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

org.eclipse.core.resources
Error
Wed Apr 27 14:34:20 CEST 2022
Could not write workspace metadata '/data/4x_platform_workspace/.metadata/.plugins/org.eclipse.core.resources/.root/2381.tree'.

java.lang.IllegalArgumentException: duplicate element: ElementTree(5174->5175...5228)
	at java.base/java.util.ImmutableCollections$SetN.<init>(ImmutableCollections.java:604)
	at java.base/java.util.Set.of(Set.java:701)
	at org.eclipse.core.internal.resources.SaveManager.sortTrees(SaveManager.java:1555)
	at org.eclipse.core.internal.watson.ElementTreeWriter.writeSortedTrees(ElementTreeWriter.java:89)
	at org.eclipse.core.internal.watson.ElementTreeWriter.writeDeltaChain(ElementTreeWriter.java:166)
	at org.eclipse.core.internal.resources.SaveManager.writeTree(SaveManager.java:2043)
	at org.eclipse.core.internal.resources.SaveManager.saveTree(SaveManager.java:1388)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1172)
	at org.eclipse.core.internal.resources.Workspace.save(Workspace.java:2409)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.lambda$1(IDEWorkbenchAdvisor.java:554)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by jukzi** [comment]
thats very interesting. please tr yto keep that state

**Comment by jukzi** [comment]
it's only a error in the errorhandler (trees does not need to be unique). well i will fix that, but the interesting thing is that you run into the errorhandler, can you set a breakpoint there? The data there would be very welcome to analyse the root reason
