### ISSUE TITLE
RefreshJob doesn't use rule to refresh

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#130]
Follow up on https://github.com/eclipse-platform/eclipse.platform.ui/issues/56.

I observe that if the `RefreshJob` is running during shutdown, it doesn't block `Workspace.save(boolean, boolean, IProgressMonitor)` task that is triggered on workspace close and that allows `org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.disconnectFromWorkspace()` to complete even if `RefreshJob` is middle in some refresh code.

Results in two errors in the log:
```
java.lang.Exception: Workspace was not properly initialized or has already shutdown.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.resources.Workspace.getWorkManager(Workspace.java:1815)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:48)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
```
java.lang.IllegalStateException: Worker thread ended job: Refreshing workspace(12), but still holds rule: ThreadJob(Refreshing workspace(12),[F/WIP/tralala])
	at org.eclipse.core.internal.jobs.ImplicitJobs.endJob(ImplicitJobs.java:139)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)
```

Originally, `RefreshJob` had a workspace root rule, that was removed via https://bugs.eclipse.org/bugs/show_bug.cgi?id=74392.

I think we can partly restore the locking behavior and use `Job.getJobManager().beginRule(refreshRule, subMonitor);` for the `RefreshJob` tasks. Doing so, I see that workspace save waits for refresh job and on shutdown it opens expected dialog that shows refresh job running (and can be cancelled):
![image](https://user-images.githubusercontent.com/964108/168257645-8eee6c85-ba25-40a6-a23a-62ca2ef33514.png)

**Comment by cdietrich** [comment]
is there a repo to pull from? local tests ran from eclipse very tedious
