### ISSUE TITLE
random failing org.eclipse.core.tests.resources.IProjectTest.testProjectDeletionOpenUserDefinedOutOfSync

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#145]
https://download.eclipse.org/eclipse/downloads/drops4/I20220521-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

```
junit.framework.AssertionFailedError: 6.3
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.TestCase.fail(TestCase.java:223)
at org.eclipse.core.tests.resources.IProjectTest.testProjectDeletionOpenUserDefinedOutOfSync(IProjectTest.java:2487)
```

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220520-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220606-1800/testresults/html/org.eclipse.core.tests.resources_ep425I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220604-0220/testresults/html/org.eclipse.core.tests.resources_ep425I-unit-win32-java11_win32.win32.x86_64_11.html
