### ISSUE TITLE
random failing org.eclipse.core.tests.resources.regression.IResourceTest testCopy_1GA6QJP

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#41]
2.0 expected:<1649823792147> but was:<1649823792000>

junit.framework.AssertionFailedError: 2.0 expected:<1649823792147> but was:<1649823792000>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:159)
at junit.framework.TestCase.assertEquals(TestCase.java:302)
at org.eclipse.core.tests.resources.regression.IResourceTest.testCopy_1GA6QJP(IResourceTest.java:271)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by iloveeclipse** [comment]
Jörg, this is known Mac OS limitation, not caused by any recent changes. There is an old bugzilla.

**Comment by jukzi** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567737

**Comment by jukzi** [comment]
The test is wrong. It's well documented in java.io.File.lastModified() that some OSes only provide Second accuracy.
