### ISSUE TITLE
random failing org.eclipse.core.tests.resources.HiddenResourceTest testRefreshLocal

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#42]
Verifying delta for / Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/.project Missing expected change Actual kind: <CHANGED> Actual change flags: <ENCODING> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/file.txt Missing expected change Actual kind: <CHANGED> Actual change flags: <ENCODING> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt Conflicting change Expected change flags: <CONTENT> actual change flags: <ENCODING> Verifying delta for / Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder Missing expected change Actual kind: <CHANGED> Actual change flags: <0> Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt Missing expected change Actual kind: <CHANGED> Actual change flags: <CONTENT>

junit.framework.AssertionFailedError: Verifying delta for /
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/.project
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <ENCODING>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/file.txt
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <ENCODING>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt
Conflicting change
Expected change flags: <CONTENT> actual change flags: <ENCODING>
Verifying delta for /
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <0>
Verifying delta for /b083a52fc6ba001c1afdc789a6a2d0af/folder/subfile.txt
Missing expected change
Actual kind: <CHANGED>
Actual change flags: <CONTENT>

at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.TestCase.assertTrue(TestCase.java:192)
at org.eclipse.core.tests.resources.HiddenResourceTest.testRefreshLocal(HiddenResourceTest.java:37)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
Could not reproduce locally.
1. I could use an easy way to run a test multiple times in a row. @trancexpress and idea?
2. It's confusing that the daily build reports the right class name and stacktrace (good) while CI build gives wrong classname "AllTests" and no stacktrace (bad). How can CI be improved to be more like daily build?

**Comment by vogella** [comment]
Log contains a lot of "!MESSAGE The workspace will exit with unsaved changes in this session." message. Maybe this causes side effects.

**Comment by iloveeclipse** [comment]
> Log contains a lot of 

No, that's unrelated & old issue.

**Comment by akurtakov** [comment]
Do you still see this one?
