### ISSUE TITLE
random failing org.eclipse.core.tests.resources.LinkedResourceTest testMoveFolder

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#43]
invocation 1 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/OtherExistingProject/nonExistingFolderInOtherExistingProject' already exists.

java.lang.AssertionError: invocation 1 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/OtherExistingProject/nonExistingFolderInOtherExistingProject' already exists.
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:101)
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:114)
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:114)
at org.eclipse.core.tests.resources.TestPerformer.performTest(TestPerformer.java:58)
at org.eclipse.core.tests.resources.LinkedResourceTest.testMoveFolder(LinkedResourceTest.java:1684)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220425-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

`invocation 7 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/ExistingProject/existingFolderInExistingProject/nonExistingFolderInExistingFolder' already exists.
`

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220428-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
invocation 7 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/ExistingProject/existingFolderInExistingProject/nonExistingFolderInExistingFolder' already exists.
```

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220430-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
this fails frequent on macosX!

**Comment by mickaelistria** [comment]
Is this failure recent or has it been there forever-ish?

**Comment by jukzi** [comment]
i do not know, i recorded random errors for ~2 weeks only

**Comment by jukzi** [comment]
also 
https://download.eclipse.org/eclipse/downloads/drops4/I20220504-0230/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220505-0320/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20220506-0640/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by akurtakov** [comment]
Do you still see this one?
