### ISSUE TITLE
random failing org.eclipse.core.tests.resources.MarkerTest testMarkerDeltasMerge

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#44]
2.2./1 expected:<1> but was:<0>

junit.framework.AssertionFailedError: 2.2./1 expected:<1> but was:<0>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:234)
at junit.framework.TestCase.assertEquals(TestCase.java:377)
at org.eclipse.core.tests.resources.MarkerTest.testMarkerDeltasMerge(MarkerTest.java:1256)

https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

**Comment by akurtakov** [comment]
Do you still see this one?

**Comment by Bananeweizen** [comment]
Are resource listeners guaranteed to be executed synchronously? If not, then it would be no surprise that the listener sometimes hasn't been called _yet_. In that case this would need some kind of active waiting for the resource change listener invocation (which might be as simple as looping until the counter is right).

**Comment by laeubi** [comment]
> Are resource listeners guaranteed to be executed synchronously?

Even if I would never assume that in a test...
