### ISSUE TITLE
ProjectPreferencesTest fails on Windows

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.resources#6]
https://download.eclipse.org/eclipse/downloads/drops4/I20220326-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

The new test for bug [579372](https://bugs.eclipse.org/bugs/show_bug.cgi?id=579372) was working on all systems that have default encoding UTF-8. Windows tests run with Cp1252 for whatever reason.

```
expected:<UTF-8> but was:<Cp1252>

junit.framework.AssertionFailedError: expected:<UTF-8> but was:<Cp1252>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:86)
at junit.framework.TestCase.assertEquals(TestCase.java:246)
at org.eclipse.core.tests.internal.resources.ProjectPreferencesTest.test_579372(ProjectPreferencesTest.java:718)
```

**Comment by jukzi** [comment]
Cp1252 is the default encoding on windows in western europe.

**Comment by iloveeclipse** [comment]
OK, works in https://download.eclipse.org/eclipse/downloads/drops4/I20220328-1800/testresults/html/org.eclipse.core.tests.resources_ep424I-unit-win32-java11_win32.win32.x86_64_11.html
