### ISSUE TITLE
IllegalArgumentException because WorkbenchPlugin.getDefault().getDecoratorManager() null

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.resources#88]
when i run FileSystemResourceManagerTest i now sometimes see in the output:
```
java.lang.IllegalArgumentException
	at org.eclipse.core.commands.common.EventManager.addListenerObject(EventManager.java:59)
	at org.eclipse.jface.viewers.BaseLabelProvider.addListener(BaseLabelProvider.java:31)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition$1.run(LightweightDecoratorDefinition.java:125)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.internalGetDecorator(LightweightDecoratorDefinition.java:119)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:240)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.queue(DecorationScheduler.java:419)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:397)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by vogella** [comment]
@laeubi maybe related to your resource work?

**Comment by laeubi** [comment]
I don't see any `resources` in the stack trace here... and `WorkbenchPlugin` is part of `org.eclipse.ui.workbench`

**Comment by laeubi** [comment]
This calls WorkbenchPlugin.getDefault().getDecoratorManager() and this access the e4 context so it seems `initializeContext` is not called when this method is called (or it is called async) ... just the usual mess with static method access in a dynamic runtime.
